### ISSUE TITLE
Misspelled GNU

### ISSUE THREAD

**Issue by YDX-2147483647** [MarekZhang/OSTEP-Homework#1]
It should be `#define _GNU_SOURCE`. (GUN → GNU)

https://github.com/MarekZhang/OSTEP-Homework/blob/03cfdf41c402bd5a6339238a010c6b9d39ce411f/C6-Limit-Direct-Execution/test.c#L1

(Sorry to bother you)

**Comment by MarekZhang** [comment]
No worries, thanks for pointing it out.
